Added automated test rerun due to random errors, probably because of slow runners.

diff --git a/.github/workflows/execute-tests.yml b/.github/workflows/execute-tests.yml
--- a/.github/workflows/execute-tests.yml
+++ b/.github/workflows/execute-tests.yml
@@ -59,7 +59,12 @@ jobs:
         run: make install
 
       - name: Run tests
-        run: make test
+        run: |
+          echo "Tests are run 3 times due to slow runners sometimes causing tests to fail without reason."
+          (echo "===== make test attempt 1 =====" && make test) || \
+          (echo "===== make test attempt 2 =====" && make test) || \
+          (echo "===== make test attempt 3 =====" && make test) || \
+          (echo "===== make test FAILED ALL ATTEMPTS!" && exit 1)
 
       - name: Upload coverage
         uses: codecov/codecov-action@v1
